#!/bin/bash

STTY="stty -F"
ECHO="echo -e"


$ECHO "Connect the Arduino Micro being used as Programmer to the
ICSP header on the Keyboardio PCB:

Connections on Arduino Micro to Keyboardio PCB:

Arduino     PCB ICSP          ICSP Header:
=======     ========          MISO  GND
3V3         3V3               3V3   RESET 
GND         GND               SCK   MOSI 
MOSI        MOSI
MISO        MISO              On the PCB, MISO is on pin 1.
SCK         SCK               Pin 1 is the SQUARE pin.
10          RESET";

read xxx

port_tmp_file=`mktemp -t kbio-port-XXXX`
./probe-device $port_tmp_file
DEVICE=`cat $port_tmp_file`
rm $port_tmp_file

if [ "x$DEVICE" == "x" ]; then exit -1; fi

$STTY $DEVICE 1200

$ECHO "Setting fuses...\c"

if  ../binaries/`uname`/avrdude/avrdude -V -C../binaries/`uname`/avrdude/avrdude.conf -patmega32u4 -cstk500v1 -P$DEVICE -b19200 -e -Ulock:w:0x3F:m -Uefuse:w:0xcb:m -Uhfuse:w:0xd8:m -Ulfuse:w:0xff:m 2>/tmp/keyboardio-log.$$ ; then
    $ECHO "done";
else 
    $ECHO "ERROR: Fuse setting failed";
    exit -1;
fi


$ECHO "Flashing bootloader...\c";

if  ../binaries/`uname`/avrdude/avrdude -V -C../binaries/`uname`/avrdude/avrdude.conf -patmega32u4 -cstk500v1 -P$DEVICE -b19200 -Uflash:w:../firmware/bootloader.hex:i -Ulock:w:0x2F:m 2>/tmp/keyboardio-log.$$ ; then
    $ECHO "done";
else 
    $ECHO "ERROR: Flashing setting failed";
    exit -1;
fi


$ECHO "Please disconnect the Arduino ISP from the test PCB"
$ECHO "From now on, you should only connect the USB cable to the LEFT PCB"

port_tmp_file=`mktemp -t kbio-port-XXXX`
./probe-device $port_tmp_file "LEFT PCB"
DEVICE=`cat $port_tmp_file`
rm $port_tmp_file

$STTY $DEVICE 1200
$STTY $DEVICE 1200
$STTY $DEVICE 1200
sleep 2

$ECHO "Flashing test firmware...\c"

if ../binaries/`uname`/avrdude/avrdude -V -C../binaries/`uname`/avrdude/avrdude.conf -patmega32u4 -cavr109 -P$DEVICE -b57600 -D -Uflash:w:../firmware/test.hex:i  2>/tmp/keyboardio-log.$$ ; then
    $ECHO "done";
else 
    $ECHO "ERROR: Flashing failed\n";
    exit -1;
fi

if [ "x$DEVICE" == "x" ]; then
    exit -1;
fi

$ECHO "Testing basic USB device connectivity.\nPlease do not touch the keyboard.";

read basic_connectivity

$ECHO "Detecting MCU...\c"
if [ "$basic_connectivity" == "#MCU Connected OK" ]; then
    $ECHO "found.";
else
    $ECHO "ERROR: something went wrong. Did flashing fail?\n";
fi

read has_io_expander

$ECHO "Testing SX1509...\c"
if [ "$has_io_expander" == "#MCU Connected OK" ]; then
    read has_io_expander
fi

if [ "$has_io_expander" == "#IO Expander found at 0x00" ]; then
    $ECHO "done."
else
    $ECHO "ERROR Something bad happened.\nThe SX1509 IO Expander could not be initialized\n";
    exit -1;
fi

    $ECHO "OK: PASS.\nThis prototype board is ready for shipment to Keyboardio.\nThank you!";
    exit 0;
