#!/bin/sh

port_tmp_file=`mktemp -t kbio-port`
./probe-device $port_tmp_file
DEVICE=`cat $port_tmp_file`
rm $port_tmp_file

stty -f $DEVICE 1200
sleep 2
if ../binaries/mac/avrdude/avrdude -V -C../binaries/mac/avrdude/avrdude.conf -patmega32u4 -cavr109 -P$DEVICE -b57600 -D -Uflash:w:../firmware/noop.hex:i; then
    echo "OK: Flashing worked\nYou can start testing again\n";
    exit 0;
else 
    echo "ERROR: Flashing failed\n";
    exit -1;
fi
